log:
  level: "trace"
  gelf:
    address: "192.168.1.4:12201"
  file:
    filename: "digger.log"
    maxsize: 1 # megabytes
    maxbackups: 3 # number of backups
    maxage: 30 # days

db:
  path: "sites.db"

smtp:
  host: "some.smtp.server"
  port: 25
  username: ""
  password: ""
  from: "somebody@somewhere.com"
  to: "somebodyelse@someplace.net"
  template_path: "templates\\email.html"

digger_path: 'C:\\Users\\someuser\\somefolder\\digger\\build\\digger-windows-amd64.exe'