log:
  level: "trace"
  gelf:
    address: "192.168.1.4:12201"
  file:
    filename: "digger.log"
    maxsize: 1 # megabytes
    maxbackups: 3 # number of backups
    maxage: 30 # days

db:
  path: "sites.db"

smtp:
   host: "lcsmtp.lc100.net"
   port: 25
   username: ""
   password: ""
   from: "bill.bohlman@lanecountyor.gov"
   to: "bill.bohlman@lanecountyor.gov"

digger_path: 'C:\\Users\\LCISBPB\\src\\digger\\build\\digger-windows-amd64.exe'